// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: cometsvc.proto

package cometsvc

import (
	messag "github.com/jxskiss/nonamegw/proto/messag"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthToken_VerifyCode int32

const (
	AuthToken_SUCCESS AuthToken_VerifyCode = 0
	AuthToken_INVALID AuthToken_VerifyCode = 1
	AuthToken_EXPIRED AuthToken_VerifyCode = 2
)

// Enum value maps for AuthToken_VerifyCode.
var (
	AuthToken_VerifyCode_name = map[int32]string{
		0: "SUCCESS",
		1: "INVALID",
		2: "EXPIRED",
	}
	AuthToken_VerifyCode_value = map[string]int32{
		"SUCCESS": 0,
		"INVALID": 1,
		"EXPIRED": 2,
	}
)

func (x AuthToken_VerifyCode) Enum() *AuthToken_VerifyCode {
	p := new(AuthToken_VerifyCode)
	*p = x
	return p
}

func (x AuthToken_VerifyCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthToken_VerifyCode) Descriptor() protoreflect.EnumDescriptor {
	return file_cometsvc_proto_enumTypes[0].Descriptor()
}

func (AuthToken_VerifyCode) Type() protoreflect.EnumType {
	return &file_cometsvc_proto_enumTypes[0]
}

func (x AuthToken_VerifyCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthToken_VerifyCode.Descriptor instead.
func (AuthToken_VerifyCode) EnumDescriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{0, 0}
}

type AuthToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token        string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SignTimeMsec int64  `protobuf:"varint,2,opt,name=sign_time_msec,json=signTimeMsec,proto3" json:"sign_time_msec,omitempty"`
	AppId        int64  `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId       int64  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId     int64  `protobuf:"varint,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{0}
}

func (x *AuthToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthToken) GetSignTimeMsec() int64 {
	if x != nil {
		return x.SignTimeMsec
	}
	return 0
}

func (x *AuthToken) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AuthToken) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthToken) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type VerifyAuthTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ClientIp string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
}

func (x *VerifyAuthTokenRequest) Reset() {
	*x = VerifyAuthTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAuthTokenRequest) ProtoMessage() {}

func (x *VerifyAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyAuthTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyAuthTokenRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type VerifyAuthTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  AuthToken_VerifyCode `protobuf:"varint,1,opt,name=code,proto3,enum=cometsvc.AuthToken_VerifyCode" json:"code,omitempty"`
	Token *AuthToken           `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *VerifyAuthTokenResponse) Reset() {
	*x = VerifyAuthTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAuthTokenResponse) ProtoMessage() {}

func (x *VerifyAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyAuthTokenResponse) GetCode() AuthToken_VerifyCode {
	if x != nil {
		return x.Code
	}
	return AuthToken_SUCCESS
}

func (x *VerifyAuthTokenResponse) GetToken() *AuthToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type GetCometConfigurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCometConfigurationRequest) Reset() {
	*x = GetCometConfigurationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCometConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCometConfigurationRequest) ProtoMessage() {}

func (x *GetCometConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCometConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetCometConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{3}
}

type GetCometConfigurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configuration *messag.CometConfiguration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
}

func (x *GetCometConfigurationResponse) Reset() {
	*x = GetCometConfigurationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCometConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCometConfigurationResponse) ProtoMessage() {}

func (x *GetCometConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCometConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetCometConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{4}
}

func (x *GetCometConfigurationResponse) GetConfiguration() *messag.CometConfiguration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type BrokerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//	*BrokerRequest_VerifyAuthTokenRequest
	//	*BrokerRequest_GetCometConfigurationRequest
	Request isBrokerRequest_Request `protobuf_oneof:"request"`
}

func (x *BrokerRequest) Reset() {
	*x = BrokerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerRequest) ProtoMessage() {}

func (x *BrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerRequest.ProtoReflect.Descriptor instead.
func (*BrokerRequest) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{5}
}

func (m *BrokerRequest) GetRequest() isBrokerRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *BrokerRequest) GetVerifyAuthTokenRequest() *VerifyAuthTokenRequest {
	if x, ok := x.GetRequest().(*BrokerRequest_VerifyAuthTokenRequest); ok {
		return x.VerifyAuthTokenRequest
	}
	return nil
}

func (x *BrokerRequest) GetGetCometConfigurationRequest() *GetCometConfigurationRequest {
	if x, ok := x.GetRequest().(*BrokerRequest_GetCometConfigurationRequest); ok {
		return x.GetCometConfigurationRequest
	}
	return nil
}

type isBrokerRequest_Request interface {
	isBrokerRequest_Request()
}

type BrokerRequest_VerifyAuthTokenRequest struct {
	VerifyAuthTokenRequest *VerifyAuthTokenRequest `protobuf:"bytes,1,opt,name=VerifyAuthTokenRequest,proto3,oneof"`
}

type BrokerRequest_GetCometConfigurationRequest struct {
	GetCometConfigurationRequest *GetCometConfigurationRequest `protobuf:"bytes,2,opt,name=GetCometConfigurationRequest,proto3,oneof"`
}

func (*BrokerRequest_VerifyAuthTokenRequest) isBrokerRequest_Request() {}

func (*BrokerRequest_GetCometConfigurationRequest) isBrokerRequest_Request() {}

type BrokerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*BrokerResponse_VerifyAuthTokenResponse
	//	*BrokerResponse_GetCometConfigurationResponse
	Response isBrokerResponse_Response `protobuf_oneof:"response"`
}

func (x *BrokerResponse) Reset() {
	*x = BrokerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerResponse) ProtoMessage() {}

func (x *BrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerResponse.ProtoReflect.Descriptor instead.
func (*BrokerResponse) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{6}
}

func (m *BrokerResponse) GetResponse() isBrokerResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *BrokerResponse) GetVerifyAuthTokenResponse() *VerifyAuthTokenResponse {
	if x, ok := x.GetResponse().(*BrokerResponse_VerifyAuthTokenResponse); ok {
		return x.VerifyAuthTokenResponse
	}
	return nil
}

func (x *BrokerResponse) GetGetCometConfigurationResponse() *GetCometConfigurationResponse {
	if x, ok := x.GetResponse().(*BrokerResponse_GetCometConfigurationResponse); ok {
		return x.GetCometConfigurationResponse
	}
	return nil
}

type isBrokerResponse_Response interface {
	isBrokerResponse_Response()
}

type BrokerResponse_VerifyAuthTokenResponse struct {
	VerifyAuthTokenResponse *VerifyAuthTokenResponse `protobuf:"bytes,1,opt,name=VerifyAuthTokenResponse,proto3,oneof"`
}

type BrokerResponse_GetCometConfigurationResponse struct {
	GetCometConfigurationResponse *GetCometConfigurationResponse `protobuf:"bytes,2,opt,name=GetCometConfigurationResponse,proto3,oneof"`
}

func (*BrokerResponse_VerifyAuthTokenResponse) isBrokerResponse_Response() {}

func (*BrokerResponse_GetCometConfigurationResponse) isBrokerResponse_Response() {}

type GetConnectionInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId string `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
}

func (x *GetConnectionInfoRequest) Reset() {
	*x = GetConnectionInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionInfoRequest) ProtoMessage() {}

func (x *GetConnectionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionInfoRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionInfoRequest) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{7}
}

func (x *GetConnectionInfoRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type GetConnectionInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetConnectionInfoResponse) Reset() {
	*x = GetConnectionInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionInfoResponse) ProtoMessage() {}

func (x *GetConnectionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionInfoResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionInfoResponse) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{8}
}

type CometRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//	*CometRequest_GetConnectionInfoRequest
	Request isCometRequest_Request `protobuf_oneof:"request"`
}

func (x *CometRequest) Reset() {
	*x = CometRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CometRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CometRequest) ProtoMessage() {}

func (x *CometRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CometRequest.ProtoReflect.Descriptor instead.
func (*CometRequest) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{9}
}

func (m *CometRequest) GetRequest() isCometRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *CometRequest) GetGetConnectionInfoRequest() *GetConnectionInfoRequest {
	if x, ok := x.GetRequest().(*CometRequest_GetConnectionInfoRequest); ok {
		return x.GetConnectionInfoRequest
	}
	return nil
}

type isCometRequest_Request interface {
	isCometRequest_Request()
}

type CometRequest_GetConnectionInfoRequest struct {
	GetConnectionInfoRequest *GetConnectionInfoRequest `protobuf:"bytes,1,opt,name=GetConnectionInfoRequest,proto3,oneof"`
}

func (*CometRequest_GetConnectionInfoRequest) isCometRequest_Request() {}

type CometResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*CometResponse_GetConnectionInfoResponse
	Response isCometResponse_Response `protobuf_oneof:"response"`
}

func (x *CometResponse) Reset() {
	*x = CometResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cometsvc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CometResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CometResponse) ProtoMessage() {}

func (x *CometResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cometsvc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CometResponse.ProtoReflect.Descriptor instead.
func (*CometResponse) Descriptor() ([]byte, []int) {
	return file_cometsvc_proto_rawDescGZIP(), []int{10}
}

func (m *CometResponse) GetResponse() isCometResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *CometResponse) GetGetConnectionInfoResponse() *GetConnectionInfoResponse {
	if x, ok := x.GetResponse().(*CometResponse_GetConnectionInfoResponse); ok {
		return x.GetConnectionInfoResponse
	}
	return nil
}

type isCometResponse_Response interface {
	isCometResponse_Response()
}

type CometResponse_GetConnectionInfoResponse struct {
	GetConnectionInfoResponse *GetConnectionInfoResponse `protobuf:"bytes,1,opt,name=GetConnectionInfoResponse,proto3,oneof"`
}

func (*CometResponse_GetConnectionInfoResponse) isCometResponse_Response() {}

var File_cometsvc_proto protoreflect.FileDescriptor

var file_cometsvc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x73, 0x76, 0x63, 0x1a, 0x0c, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x09, 0x41, 0x75, 0x74,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0e,
	0x73, 0x69, 0x67, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x65, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73,
	0x65, 0x63, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22,
	0x33, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x49, 0x52,
	0x45, 0x44, 0x10, 0x02, 0x22, 0x4b, 0x0a, 0x16, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75,
	0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x70, 0x22, 0x78, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d,
	0x65, 0x74, 0x73, 0x76, 0x63, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x29, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x73, 0x76, 0x63, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1e, 0x0a, 0x1c, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x61, 0x0a, 0x1d, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x2e, 0x43, 0x6f, 0x6d,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe4,
	0x01, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x5a, 0x0a, 0x16, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x73, 0x76, 0x63, 0x2e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x16, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x6c, 0x0a, 0x1c,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x1c, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xec, 0x01, 0x0a, 0x0e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x65,
	0x74, 0x73, 0x76, 0x63, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x17,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7b, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x60, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74,
	0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x18,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74,
	0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x19, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x78, 0x73, 0x6b, 0x69, 0x73, 0x73, 0x2f, 0x6e, 0x6f, 0x6e,
	0x61, 0x6d, 0x65, 0x67, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x65,
	0x74, 0x73, 0x76, 0x63, 0x3b, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x73, 0x76, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cometsvc_proto_rawDescOnce sync.Once
	file_cometsvc_proto_rawDescData = file_cometsvc_proto_rawDesc
)

func file_cometsvc_proto_rawDescGZIP() []byte {
	file_cometsvc_proto_rawDescOnce.Do(func() {
		file_cometsvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_cometsvc_proto_rawDescData)
	})
	return file_cometsvc_proto_rawDescData
}

var file_cometsvc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cometsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cometsvc_proto_goTypes = []interface{}{
	(AuthToken_VerifyCode)(0),             // 0: cometsvc.AuthToken.VerifyCode
	(*AuthToken)(nil),                     // 1: cometsvc.AuthToken
	(*VerifyAuthTokenRequest)(nil),        // 2: cometsvc.VerifyAuthTokenRequest
	(*VerifyAuthTokenResponse)(nil),       // 3: cometsvc.VerifyAuthTokenResponse
	(*GetCometConfigurationRequest)(nil),  // 4: cometsvc.GetCometConfigurationRequest
	(*GetCometConfigurationResponse)(nil), // 5: cometsvc.GetCometConfigurationResponse
	(*BrokerRequest)(nil),                 // 6: cometsvc.BrokerRequest
	(*BrokerResponse)(nil),                // 7: cometsvc.BrokerResponse
	(*GetConnectionInfoRequest)(nil),      // 8: cometsvc.GetConnectionInfoRequest
	(*GetConnectionInfoResponse)(nil),     // 9: cometsvc.GetConnectionInfoResponse
	(*CometRequest)(nil),                  // 10: cometsvc.CometRequest
	(*CometResponse)(nil),                 // 11: cometsvc.CometResponse
	(*messag.CometConfiguration)(nil),     // 12: messag.CometConfiguration
}
var file_cometsvc_proto_depIdxs = []int32{
	0,  // 0: cometsvc.VerifyAuthTokenResponse.code:type_name -> cometsvc.AuthToken.VerifyCode
	1,  // 1: cometsvc.VerifyAuthTokenResponse.token:type_name -> cometsvc.AuthToken
	12, // 2: cometsvc.GetCometConfigurationResponse.configuration:type_name -> messag.CometConfiguration
	2,  // 3: cometsvc.BrokerRequest.VerifyAuthTokenRequest:type_name -> cometsvc.VerifyAuthTokenRequest
	4,  // 4: cometsvc.BrokerRequest.GetCometConfigurationRequest:type_name -> cometsvc.GetCometConfigurationRequest
	3,  // 5: cometsvc.BrokerResponse.VerifyAuthTokenResponse:type_name -> cometsvc.VerifyAuthTokenResponse
	5,  // 6: cometsvc.BrokerResponse.GetCometConfigurationResponse:type_name -> cometsvc.GetCometConfigurationResponse
	8,  // 7: cometsvc.CometRequest.GetConnectionInfoRequest:type_name -> cometsvc.GetConnectionInfoRequest
	9,  // 8: cometsvc.CometResponse.GetConnectionInfoResponse:type_name -> cometsvc.GetConnectionInfoResponse
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_cometsvc_proto_init() }
func file_cometsvc_proto_init() {
	if File_cometsvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cometsvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cometsvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyAuthTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cometsvc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyAuthTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cometsvc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCometConfigurationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cometsvc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCometConfigurationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cometsvc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cometsvc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cometsvc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectionInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cometsvc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectionInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cometsvc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CometRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cometsvc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CometResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cometsvc_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*BrokerRequest_VerifyAuthTokenRequest)(nil),
		(*BrokerRequest_GetCometConfigurationRequest)(nil),
	}
	file_cometsvc_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*BrokerResponse_VerifyAuthTokenResponse)(nil),
		(*BrokerResponse_GetCometConfigurationResponse)(nil),
	}
	file_cometsvc_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*CometRequest_GetConnectionInfoRequest)(nil),
	}
	file_cometsvc_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*CometResponse_GetConnectionInfoResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cometsvc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cometsvc_proto_goTypes,
		DependencyIndexes: file_cometsvc_proto_depIdxs,
		EnumInfos:         file_cometsvc_proto_enumTypes,
		MessageInfos:      file_cometsvc_proto_msgTypes,
	}.Build()
	File_cometsvc_proto = out.File
	file_cometsvc_proto_rawDesc = nil
	file_cometsvc_proto_goTypes = nil
	file_cometsvc_proto_depIdxs = nil
}
