// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: messag.proto

package messag

import (
	protocol "github.com/jxskiss/nonamegw/proto/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpgoingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet *protocol.Packet     `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Conn   *protocol.Connection `protobuf:"bytes,2,opt,name=conn,proto3" json:"conn,omitempty"`
}

func (x *UpgoingMessage) Reset() {
	*x = UpgoingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgoingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgoingMessage) ProtoMessage() {}

func (x *UpgoingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgoingMessage.ProtoReflect.Descriptor instead.
func (*UpgoingMessage) Descriptor() ([]byte, []int) {
	return file_messag_proto_rawDescGZIP(), []int{0}
}

func (x *UpgoingMessage) GetPacket() *protocol.Packet {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *UpgoingMessage) GetConn() *protocol.Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

type DowngoingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*DowngoingMessage_Packet
	//	*DowngoingMessage_BinPacket
	Data    isDowngoingMessage_Data `protobuf_oneof:"data"`
	ConnIds []string                `protobuf:"bytes,3,rep,name=conn_ids,json=connIds,proto3" json:"conn_ids,omitempty"`
}

func (x *DowngoingMessage) Reset() {
	*x = DowngoingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DowngoingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DowngoingMessage) ProtoMessage() {}

func (x *DowngoingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DowngoingMessage.ProtoReflect.Descriptor instead.
func (*DowngoingMessage) Descriptor() ([]byte, []int) {
	return file_messag_proto_rawDescGZIP(), []int{1}
}

func (m *DowngoingMessage) GetData() isDowngoingMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *DowngoingMessage) GetPacket() *protocol.Packet {
	if x, ok := x.GetData().(*DowngoingMessage_Packet); ok {
		return x.Packet
	}
	return nil
}

func (x *DowngoingMessage) GetBinPacket() []byte {
	if x, ok := x.GetData().(*DowngoingMessage_BinPacket); ok {
		return x.BinPacket
	}
	return nil
}

func (x *DowngoingMessage) GetConnIds() []string {
	if x != nil {
		return x.ConnIds
	}
	return nil
}

type isDowngoingMessage_Data interface {
	isDowngoingMessage_Data()
}

type DowngoingMessage_Packet struct {
	Packet *protocol.Packet `protobuf:"bytes,1,opt,name=packet,proto3,oneof"`
}

type DowngoingMessage_BinPacket struct {
	BinPacket []byte `protobuf:"bytes,2,opt,name=bin_packet,json=binPacket,proto3,oneof"`
}

func (*DowngoingMessage_Packet) isDowngoingMessage_Data() {}

func (*DowngoingMessage_BinPacket) isDowngoingMessage_Data() {}

type BroadcastMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_messag_proto_rawDescGZIP(), []int{2}
}

type TokenKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	EnableTimeSec int64  `protobuf:"varint,2,opt,name=enable_time_sec,json=enableTimeSec,proto3" json:"enable_time_sec,omitempty"`
}

func (x *TokenKey) Reset() {
	*x = TokenKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenKey) ProtoMessage() {}

func (x *TokenKey) ProtoReflect() protoreflect.Message {
	mi := &file_messag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenKey.ProtoReflect.Descriptor instead.
func (*TokenKey) Descriptor() ([]byte, []int) {
	return file_messag_proto_rawDescGZIP(), []int{3}
}

func (x *TokenKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TokenKey) GetEnableTimeSec() int64 {
	if x != nil {
		return x.EnableTimeSec
	}
	return 0
}

type CometConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenKey     string      `protobuf:"bytes,1,opt,name=token_key,json=tokenKey,proto3" json:"token_key,omitempty"`
	OldTokenKeys []*TokenKey `protobuf:"bytes,2,rep,name=old_token_keys,json=oldTokenKeys,proto3" json:"old_token_keys,omitempty"`
}

func (x *CometConfiguration) Reset() {
	*x = CometConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CometConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CometConfiguration) ProtoMessage() {}

func (x *CometConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_messag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CometConfiguration.ProtoReflect.Descriptor instead.
func (*CometConfiguration) Descriptor() ([]byte, []int) {
	return file_messag_proto_rawDescGZIP(), []int{4}
}

func (x *CometConfiguration) GetTokenKey() string {
	if x != nil {
		return x.TokenKey
	}
	return ""
}

func (x *CometConfiguration) GetOldTokenKeys() []*TokenKey {
	if x != nil {
		return x.OldTokenKeys
	}
	return nil
}

var File_messag_proto protoreflect.FileDescriptor

var file_messag_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x1a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x0e, 0x55, 0x70, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x28, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x22, 0x82, 0x01, 0x0a, 0x10, 0x44,
	0x6f, 0x77, 0x6e, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2a, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x48, 0x00, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x62,
	0x69, 0x6e, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x09, 0x62, 0x69, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x12, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x44, 0x0a, 0x08, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x73, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x22, 0x69, 0x0a, 0x12, 0x43, 0x6f, 0x6d,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x0e,
	0x6f, 0x6c, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x2e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x0c, 0x6f, 0x6c, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x4b, 0x65, 0x79, 0x73, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x78, 0x73, 0x6b, 0x69, 0x73, 0x73, 0x2f, 0x6e, 0x6f, 0x6e, 0x61, 0x6d,
	0x65, 0x67, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messag_proto_rawDescOnce sync.Once
	file_messag_proto_rawDescData = file_messag_proto_rawDesc
)

func file_messag_proto_rawDescGZIP() []byte {
	file_messag_proto_rawDescOnce.Do(func() {
		file_messag_proto_rawDescData = protoimpl.X.CompressGZIP(file_messag_proto_rawDescData)
	})
	return file_messag_proto_rawDescData
}

var file_messag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_messag_proto_goTypes = []interface{}{
	(*UpgoingMessage)(nil),      // 0: messag.UpgoingMessage
	(*DowngoingMessage)(nil),    // 1: messag.DowngoingMessage
	(*BroadcastMessage)(nil),    // 2: messag.BroadcastMessage
	(*TokenKey)(nil),            // 3: messag.TokenKey
	(*CometConfiguration)(nil),  // 4: messag.CometConfiguration
	(*protocol.Packet)(nil),     // 5: protocol.Packet
	(*protocol.Connection)(nil), // 6: protocol.Connection
}
var file_messag_proto_depIdxs = []int32{
	5, // 0: messag.UpgoingMessage.packet:type_name -> protocol.Packet
	6, // 1: messag.UpgoingMessage.conn:type_name -> protocol.Connection
	5, // 2: messag.DowngoingMessage.packet:type_name -> protocol.Packet
	3, // 3: messag.CometConfiguration.old_token_keys:type_name -> messag.TokenKey
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_messag_proto_init() }
func file_messag_proto_init() {
	if File_messag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgoingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DowngoingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messag_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CometConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messag_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*DowngoingMessage_Packet)(nil),
		(*DowngoingMessage_BinPacket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messag_proto_goTypes,
		DependencyIndexes: file_messag_proto_depIdxs,
		MessageInfos:      file_messag_proto_msgTypes,
	}.Build()
	File_messag_proto = out.File
	file_messag_proto_rawDesc = nil
	file_messag_proto_goTypes = nil
	file_messag_proto_depIdxs = nil
}
