// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: bizapi.proto

package bizapi

import (
	protocol "github.com/jxskiss/nonamegw/proto/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *protocol.Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OnMessageRequest) Reset() {
	*x = OnMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bizapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnMessageRequest) ProtoMessage() {}

func (x *OnMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bizapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnMessageRequest.ProtoReflect.Descriptor instead.
func (*OnMessageRequest) Descriptor() ([]byte, []int) {
	return file_bizapi_proto_rawDescGZIP(), []int{0}
}

func (x *OnMessageRequest) GetMessage() *protocol.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type OnMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnMessageResponse) Reset() {
	*x = OnMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bizapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnMessageResponse) ProtoMessage() {}

func (x *OnMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bizapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnMessageResponse.ProtoReflect.Descriptor instead.
func (*OnMessageResponse) Descriptor() ([]byte, []int) {
	return file_bizapi_proto_rawDescGZIP(), []int{1}
}

type OnEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *protocol.Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *OnEventRequest) Reset() {
	*x = OnEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bizapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnEventRequest) ProtoMessage() {}

func (x *OnEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bizapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnEventRequest.ProtoReflect.Descriptor instead.
func (*OnEventRequest) Descriptor() ([]byte, []int) {
	return file_bizapi_proto_rawDescGZIP(), []int{2}
}

func (x *OnEventRequest) GetEvent() *protocol.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type OnEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnEventResponse) Reset() {
	*x = OnEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bizapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnEventResponse) ProtoMessage() {}

func (x *OnEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bizapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnEventResponse.ProtoReflect.Descriptor instead.
func (*OnEventResponse) Descriptor() ([]byte, []int) {
	return file_bizapi_proto_rawDescGZIP(), []int{3}
}

var File_bizapi_proto protoreflect.FileDescriptor

var file_bizapi_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x69, 0x7a, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x69, 0x7a, 0x61, 0x70, 0x69, 0x1a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x10, 0x4f, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x4f, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x0e,
	0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x86, 0x01, 0x0a, 0x06, 0x42, 0x69, 0x7a,
	0x41, 0x70, 0x69, 0x12, 0x40, 0x0a, 0x09, 0x4f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x2e, 0x62, 0x69, 0x7a, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x69, 0x7a,
	0x61, 0x70, 0x69, 0x2e, 0x4f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x16, 0x2e, 0x62, 0x69, 0x7a, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x69, 0x7a, 0x61, 0x70,
	0x69, 0x2e, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6a, 0x78, 0x73, 0x6b, 0x69, 0x73, 0x73, 0x2f, 0x6e, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x67, 0x77,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x7a, 0x61, 0x70, 0x69, 0x3b, 0x62, 0x69,
	0x7a, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bizapi_proto_rawDescOnce sync.Once
	file_bizapi_proto_rawDescData = file_bizapi_proto_rawDesc
)

func file_bizapi_proto_rawDescGZIP() []byte {
	file_bizapi_proto_rawDescOnce.Do(func() {
		file_bizapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_bizapi_proto_rawDescData)
	})
	return file_bizapi_proto_rawDescData
}

var file_bizapi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bizapi_proto_goTypes = []interface{}{
	(*OnMessageRequest)(nil),  // 0: bizapi.OnMessageRequest
	(*OnMessageResponse)(nil), // 1: bizapi.OnMessageResponse
	(*OnEventRequest)(nil),    // 2: bizapi.OnEventRequest
	(*OnEventResponse)(nil),   // 3: bizapi.OnEventResponse
	(*protocol.Message)(nil),  // 4: protocol.Message
	(*protocol.Event)(nil),    // 5: protocol.Event
}
var file_bizapi_proto_depIdxs = []int32{
	4, // 0: bizapi.OnMessageRequest.message:type_name -> protocol.Message
	5, // 1: bizapi.OnEventRequest.event:type_name -> protocol.Event
	0, // 2: bizapi.BizApi.OnMessage:input_type -> bizapi.OnMessageRequest
	2, // 3: bizapi.BizApi.OnEvent:input_type -> bizapi.OnEventRequest
	1, // 4: bizapi.BizApi.OnMessage:output_type -> bizapi.OnMessageResponse
	3, // 5: bizapi.BizApi.OnEvent:output_type -> bizapi.OnEventResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bizapi_proto_init() }
func file_bizapi_proto_init() {
	if File_bizapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bizapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bizapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bizapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bizapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bizapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bizapi_proto_goTypes,
		DependencyIndexes: file_bizapi_proto_depIdxs,
		MessageInfos:      file_bizapi_proto_msgTypes,
	}.Build()
	File_bizapi_proto = out.File
	file_bizapi_proto_rawDesc = nil
	file_bizapi_proto_goTypes = nil
	file_bizapi_proto_depIdxs = nil
}
